import{a as S,S as P,i}from"./assets/vendor-5YrzWRhu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const B="https://pixabay.com/api/",E="51453767-d8931522dcfdee5b391d73c50";async function f(s,o){return(await S.get(B,{params:{key:E,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}const p=document.querySelector(".gallery"),h=document.querySelector(".load-more"),m=document.querySelector(".loader"),M=new P(".gallery a",{captionsData:"alt",captionDelay:250});function g(s){const o=s.map(({webformatURL:r,largeImageURL:c,tags:e,likes:t,views:n,comments:w,downloads:q})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${r}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${w}</p>
          <p><b>Downloads:</b> ${q}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",o),M.refresh()}function R(){p.innerHTML=""}function y(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function b(){h.classList.remove("hidden")}function l(){h.classList.add("hidden")}const $=document.querySelector(".form"),O=document.querySelector(".load-more");let d="",a=1;const v=15;let u=0;$.addEventListener("submit",async s=>{s.preventDefault();const o=s.target.searchQuery.value.trim();if(!o){i.warning({message:"Please enter a search query.",position:"topRight"});return}d=o,a=1,R(),l(),y();try{const r=await f(d,a);if(u=r.totalHits,r.hits.length===0){i.info({message:"No images found. Try another query.",position:"topRight"});return}g(r.hits),u>v?b():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({message:"Error fetching images.",position:"topRight"})}finally{L()}});O.addEventListener("click",async()=>{a+=1,y(),l();try{const s=await f(d,a);g(s.hits);const o=Math.ceil(u/v);a>=o?(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b();const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch{i.error({message:"Error loading more images.",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
